name: Deploy Quiz to shinyapps.io

on:
  pull_request:
    types: [opened, synchronize, ready_for_review]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.0'
          use-public-rspm: true
          
      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@v2
        
      - name: Install dependencies from DESCRIPTION
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          dependencies: '"hard"'  # Install Imports, Depends, LinkingTo
        
      - name: Configure rsconnect authentication
        run: |
          rsconnect::setAccountInfo(
            name = '${{ secrets.SHINYAPPS_ACCOUNT }}',
            token = '${{ secrets.SHINYAPPS_TOKEN }}',
            secret = '${{ secrets.SHINYAPPS_SECRET }}'
          )
        shell: Rscript {0}
        
      - name: Run build script
        run: |
          cat("🚀 Starting deployment process...\n")
          source("build.R")
          cat("✅ All deployments completed successfully!\n")
        shell: Rscript {0}
        
      - name: Upload deployment logs
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: deployment-logs-${{ github.run_id }}
          path: |
            *.log
            rsconnect/
            modules/rsconnect/